using System;
using System.Collections.Generic;
using System.Text;

namespace Ame.Satel.Integra.Api.System
{
    public enum Commands
    {
        zones_violation = 0x00,
        zones_alarm = 0x02,
        zones_tamper_alarm = 0x03,
        zones_alarm_memory = 0x04,
        zones_tamper_alarm_memory = 0x05,
        zones_bypass = 0x06,
        zones_no_violation_trouble = 0x07,
        zones_long_violation_trouble = 0x08,
        armed_partitions_suppressed = 0x09,
        armed_partitions_really = 0x0A,
        partitions_armed_in_mode_2 = 0x0B,
        partitions_armed_in_mode_3 = 0x0C,
        partitions_with_1st_code_entered = 0x0D,
        partitions_entry_time = 0x0E,
        partitions_exit_time_gt_10s = 0x0F,
        partitions_exit_time_lt_10s = 0x10,
        partitions_temporary_blocked = 0x11,
        partitions_blocked_for_guard_round = 0x12,
        partitions_alarm = 0x13,
        partitions_fire_alarm = 0x14,
        partitions_alarm_memory = 0x15,
        partitions_fire_alarm_memory = 0x16,
        outputs_state = 0x17,
        doors_opened = 0x18,
        doors_opened_long = 0x19,
        RTC_and_basic_status_bits = 0x1A,
        troubles_part_1 = 0x1B,
        troubles_part_2 = 0x1C,
        troubles_part_3 = 0x1D,
        troubles_part_4 = 0x1E,
        troubles_part_5 = 0x1F,
        troubles_memory_part_1 = 0x20,
        troubles_memory_part_2 = 0x21,
        troubles_memory_part_3 = 0x22,
        troubles_memory_part_4 = 0x23,
        troubles_memory_part_5 = 0x24,
        partitions_with_violated_zones = 0x25,
        zones_isolate = 0x26,
        partitions_with_verified_alarms = 0x27,
        zones_masked = 0x28,
        zones_masked_memory = 0x29,
        partitions_armed_in_mode_1 = 0x2A,
        partitions_with_warning_alarms = 0x2B,
        troubles_part_6 = 0x2C,
        troubles_part_7 = 0x2D,
        troubles_memory_part_6 = 0x2E,
        troubles_memory_part_7 = 0x2F,
        troubles_part_8 = 0x30,
        troubles_memory_part_8 = 0x31,
    }
}
